#ifndef _CEPTR_SYMBOL_H
#define _CEPTR_SYMBOL_H

#define TEST_SYMBOL 99

enum {SEMTREX_SYMBOL_LITERAL,SEMTREX_SEQUENCE,SEMTREX_OR,SEMTREX_SYMBOL_ANY,SEMTREX_STAR,SEMTREX_PLUS,SEMTREX_QUESTION,SEMTREX_GROUP,SEMTREX_MATCH_RESULTS,SEMTREX_MATCH,SEMTREX_MATCH_SIBLINGS_COUNT,SEMTREX_VALUE_LITERAL,TREE_PATH};

typedef int Symbol;

#endif
